### ISSUE TITLE
Build Error on Fresh Build

### ISSUE THREAD

**Issue by jodylecompte** [mdaffin/sprockit.io#16]
When trying to run a fresh build via a fresh fork, an error is being thrown from index.vue 

![image](https://user-images.githubusercontent.com/38302762/66710131-f4f21200-ed37-11e9-9564-ea6c7ff3354b.png)

It is triggered by the following bit of code:
```js
      doc.open();
      doc.write(`<script>${this.code}</script` + ">");
      doc.close();
```

**Comment by austinnguyen2001** [comment]
try replacing that doc write with this `<script>${this.code}<\/script>`

**Comment by jodylecompte** [comment]
For reasons I can't explain, it's really unhappy about the <script> tag even if I remove ${this.code} from the equation completely and just simply try `doc.write('<script></script>');`.

I found a solution that uses escape/unescape borrowing from one of the re-targeting (marketing) pixels we use at work that isn't the most elegant thing I've ever done but seems to work. I will open a PR for everyone's review shortly.

**Comment by mdaffin** [comment]
@jodylecompte I believe the reason it does not like the script tag as the parser sees it and treats it with a higher precedence than the quotes it is meant to be within. This results in it truncating the script at that point which creates an invalid script as we are missing the end.

`<script>${this.code}<\/script>` did work, but the linter complained about an use of a unnecessary escape - which was a false positive due to the weird nature of what we are trying to do here. Not sure why the string concatenation failed - possibly due to a transpiler optimization removing it?
